# Generated by Django 2.1 on 2018-09-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20180925_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='interest',
            field=models.CharField(choices=[('topic1', 'topic1'), ('topic2', 'topic2')], max_length=10, unique=True),
        ),
    ]
