# Generated by Django 2.1 on 2018-09-26 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0003_auto_20180926_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='interest',
            field=models.CharField(choices=[('topic1', 'topic1'), ('topic2', 'topic2')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='interests',
            unique_together={('user', 'interest')},
        ),
    ]
