# Generated by Django 2.1 on 2018-09-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='interests',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
