# Generated by Django 2.1 on 2018-09-26 06:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180926_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 6, 55, 40, 51504, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='path',
            field=models.CharField(default='', max_length=140),
        ),
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 26, 6, 55, 40, 50808, tzinfo=utc)),
        ),
    ]
