# Generated by Django 2.1 on 2018-09-27 14:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20180927_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explaination',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='answer',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 14, 31, 20, 417758, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 27, 14, 31, 20, 416345, tzinfo=utc)),
        ),
    ]
