# Generated by Django 2.1 on 2018-09-28 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20180928_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 7, 28, 23, 583944, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 28, 7, 28, 23, 582399, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='interests',
            field=models.CharField(choices=[('topic1', 'topic1'), ('topic2', 'topic2')], default='', max_length=10),
        ),
    ]
